name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        lfs: true

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Push to deployment branch
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git checkout -b deployment
        git push https://$PAT@github.com/BillKG-exe/AI-Cartoon-UC-Davis-CoE.git deployment --force

